In [16]:
from pathlib import Path
import json
import pandas as pd
import sqlalchemy as sql
from sqlalchemy import create_engine
from time import gmtime, strftime
import time

In [17]:
with open(Path("XRP_tweet_count.json")) as f:
    data = json.load(f)

In [18]:
data

{'data': [{'end': '2021-10-02T23:00:00.000Z',
   'start': '2021-10-02T22:26:13.000Z',
   'tweet_count': 844},
  {'end': '2021-10-03T00:00:00.000Z',
   'start': '2021-10-02T23:00:00.000Z',
   'tweet_count': 1614},
  {'end': '2021-10-03T01:00:00.000Z',
   'start': '2021-10-03T00:00:00.000Z',
   'tweet_count': 1473},
  {'end': '2021-10-03T02:00:00.000Z',
   'start': '2021-10-03T01:00:00.000Z',
   'tweet_count': 1342},
  {'end': '2021-10-03T03:00:00.000Z',
   'start': '2021-10-03T02:00:00.000Z',
   'tweet_count': 1343},
  {'end': '2021-10-03T04:00:00.000Z',
   'start': '2021-10-03T03:00:00.000Z',
   'tweet_count': 1314},
  {'end': '2021-10-03T05:00:00.000Z',
   'start': '2021-10-03T04:00:00.000Z',
   'tweet_count': 1241},
  {'end': '2021-10-03T06:00:00.000Z',
   'start': '2021-10-03T05:00:00.000Z',
   'tweet_count': 1293},
  {'end': '2021-10-03T07:00:00.000Z',
   'start': '2021-10-03T06:00:00.000Z',
   'tweet_count': 1272},
  {'end': '2021-10-03T08:00:00.000Z',
   'start': '2021-10-03T07:00:00.000Z',
   'tweet_count': 1448},
  {'end': '2021-10-03T09:00:00.000Z',
   'start': '2021-10-03T08:00:00.000Z',
   'tweet_count': 1413},
  {'end': '2021-10-03T10:00:00.000Z',
   'start': '2021-10-03T09:00:00.000Z',
   'tweet_count': 1350},
  {'end': '2021-10-03T11:00:00.000Z',
   'start': '2021-10-03T10:00:00.000Z',
   'tweet_count': 1884},
  {'end': '2021-10-03T12:00:00.000Z',
   'start': '2021-10-03T11:00:00.000Z',
   'tweet_count': 2065},
  {'end': '2021-10-03T13:00:00.000Z',
   'start': '2021-10-03T12:00:00.000Z',
   'tweet_count': 1881},
  {'end': '2021-10-03T14:00:00.000Z',
   'start': '2021-10-03T13:00:00.000Z',
   'tweet_count': 2582},
  {'end': '2021-10-03T15:00:00.000Z',
   'start': '2021-10-03T14:00:00.000Z',
   'tweet_count': 2391},
  {'end': '2021-10-03T16:00:00.000Z',
   'start': '2021-10-03T15:00:00.000Z',
   'tweet_count': 3237},
  {'end': '2021-10-03T17:00:00.000Z',
   'start': '2021-10-03T16:00:00.000Z',
   'tweet_count': 2647},
  {'end': '2021-10-03T18:00:00.000Z',
   'start': '2021-10-03T17:00:00.000Z',
   'tweet_count': 2163},
  {'end': '2021-10-03T19:00:00.000Z',
   'start': '2021-10-03T18:00:00.000Z',
   'tweet_count': 2294},
  {'end': '2021-10-03T20:00:00.000Z',
   'start': '2021-10-03T19:00:00.000Z',
   'tweet_count': 2187},
  {'end': '2021-10-03T21:00:00.000Z',
   'start': '2021-10-03T20:00:00.000Z',
   'tweet_count': 1743},
  {'end': '2021-10-03T22:00:00.000Z',
   'start': '2021-10-03T21:00:00.000Z',
   'tweet_count': 1869},
  {'end': '2021-10-03T23:00:00.000Z',
   'start': '2021-10-03T22:00:00.000Z',
   'tweet_count': 1867},
  {'end': '2021-10-04T00:00:00.000Z',
   'start': '2021-10-03T23:00:00.000Z',
   'tweet_count': 1822},
  {'end': '2021-10-04T01:00:00.000Z',
   'start': '2021-10-04T00:00:00.000Z',
   'tweet_count': 1833},
  {'end': '2021-10-04T02:00:00.000Z',
   'start': '2021-10-04T01:00:00.000Z',
   'tweet_count': 2484},
  {'end': '2021-10-04T03:00:00.000Z',
   'start': '2021-10-04T02:00:00.000Z',
   'tweet_count': 1887},
  {'end': '2021-10-04T04:00:00.000Z',
   'start': '2021-10-04T03:00:00.000Z',
   'tweet_count': 1594},
  {'end': '2021-10-04T05:00:00.000Z',
   'start': '2021-10-04T04:00:00.000Z',
   'tweet_count': 1365},
  {'end': '2021-10-04T06:00:00.000Z',
   'start': '2021-10-04T05:00:00.000Z',
   'tweet_count': 1323},
  {'end': '2021-10-04T07:00:00.000Z',
   'start': '2021-10-04T06:00:00.000Z',
   'tweet_count': 1518},
  {'end': '2021-10-04T08:00:00.000Z',
   'start': '2021-10-04T07:00:00.000Z',
   'tweet_count': 1917},
  {'end': '2021-10-04T09:00:00.000Z',
   'start': '2021-10-04T08:00:00.000Z',
   'tweet_count': 2045},
  {'end': '2021-10-04T10:00:00.000Z',
   'start': '2021-10-04T09:00:00.000Z',
   'tweet_count': 1784},
  {'end': '2021-10-04T11:00:00.000Z',
   'start': '2021-10-04T10:00:00.000Z',
   'tweet_count': 2149},
  {'end': '2021-10-04T12:00:00.000Z',
   'start': '2021-10-04T11:00:00.000Z',
   'tweet_count': 2388},
  {'end': '2021-10-04T13:00:00.000Z',
   'start': '2021-10-04T12:00:00.000Z',
   'tweet_count': 2378},
  {'end': '2021-10-04T14:00:00.000Z',
   'start': '2021-10-04T13:00:00.000Z',
   'tweet_count': 2667},
  {'end': '2021-10-04T15:00:00.000Z',
   'start': '2021-10-04T14:00:00.000Z',
   'tweet_count': 2498},
  {'end': '2021-10-04T16:00:00.000Z',
   'start': '2021-10-04T15:00:00.000Z',
   'tweet_count': 2350},
  {'end': '2021-10-04T17:00:00.000Z',
   'start': '2021-10-04T16:00:00.000Z',
   'tweet_count': 2438},
  {'end': '2021-10-04T18:00:00.000Z',
   'start': '2021-10-04T17:00:00.000Z',
   'tweet_count': 4146},
  {'end': '2021-10-04T19:00:00.000Z',
   'start': '2021-10-04T18:00:00.000Z',
   'tweet_count': 5075},
  {'end': '2021-10-04T20:00:00.000Z',
   'start': '2021-10-04T19:00:00.000Z',
   'tweet_count': 3525},
  {'end': '2021-10-04T21:00:00.000Z',
   'start': '2021-10-04T20:00:00.000Z',
   'tweet_count': 3330},
  {'end': '2021-10-04T22:00:00.000Z',
   'start': '2021-10-04T21:00:00.000Z',
   'tweet_count': 2781},
  {'end': '2021-10-04T23:00:00.000Z',
   'start': '2021-10-04T22:00:00.000Z',
   'tweet_count': 2555},
  {'end': '2021-10-05T00:00:00.000Z',
   'start': '2021-10-04T23:00:00.000Z',
   'tweet_count': 2468},
  {'end': '2021-10-05T01:00:00.000Z',
   'start': '2021-10-05T00:00:00.000Z',
   'tweet_count': 2366},
  {'end': '2021-10-05T02:00:00.000Z',
   'start': '2021-10-05T01:00:00.000Z',
   'tweet_count': 3974},
  {'end': '2021-10-05T03:00:00.000Z',
   'start': '2021-10-05T02:00:00.000Z',
   'tweet_count': 2814},
  {'end': '2021-10-05T04:00:00.000Z',
   'start': '2021-10-05T03:00:00.000Z',
   'tweet_count': 2703},
  {'end': '2021-10-05T05:00:00.000Z',
   'start': '2021-10-05T04:00:00.000Z',
   'tweet_count': 2465},
  {'end': '2021-10-05T06:00:00.000Z',
   'start': '2021-10-05T05:00:00.000Z',
   'tweet_count': 2386},
  {'end': '2021-10-05T07:00:00.000Z',
   'start': '2021-10-05T06:00:00.000Z',
   'tweet_count': 2578},
  {'end': '2021-10-05T08:00:00.000Z',
   'start': '2021-10-05T07:00:00.000Z',
   'tweet_count': 2375},
  {'end': '2021-10-05T09:00:00.000Z',
   'start': '2021-10-05T08:00:00.000Z',
   'tweet_count': 2200},
  {'end': '2021-10-05T10:00:00.000Z',
   'start': '2021-10-05T09:00:00.000Z',
   'tweet_count': 2192},
  {'end': '2021-10-05T11:00:00.000Z',
   'start': '2021-10-05T10:00:00.000Z',
   'tweet_count': 2657},
  {'end': '2021-10-05T12:00:00.000Z',
   'start': '2021-10-05T11:00:00.000Z',
   'tweet_count': 2928},
  {'end': '2021-10-05T13:00:00.000Z',
   'start': '2021-10-05T12:00:00.000Z',
   'tweet_count': 3729},
  {'end': '2021-10-05T14:00:00.000Z',
   'start': '2021-10-05T13:00:00.000Z',
   'tweet_count': 3928},
  {'end': '2021-10-05T15:00:00.000Z',
   'start': '2021-10-05T14:00:00.000Z',
   'tweet_count': 3571},
  {'end': '2021-10-05T16:00:00.000Z',
   'start': '2021-10-05T15:00:00.000Z',
   'tweet_count': 3278},
  {'end': '2021-10-05T17:00:00.000Z',
   'start': '2021-10-05T16:00:00.000Z',
   'tweet_count': 3474},
  {'end': '2021-10-05T18:00:00.000Z',
   'start': '2021-10-05T17:00:00.000Z',
   'tweet_count': 3392},
  {'end': '2021-10-05T19:00:00.000Z',
   'start': '2021-10-05T18:00:00.000Z',
   'tweet_count': 3066},
  {'end': '2021-10-05T20:00:00.000Z',
   'start': '2021-10-05T19:00:00.000Z',
   'tweet_count': 3237},
  {'end': '2021-10-05T21:00:00.000Z',
   'start': '2021-10-05T20:00:00.000Z',
   'tweet_count': 3640},
  {'end': '2021-10-05T22:00:00.000Z',
   'start': '2021-10-05T21:00:00.000Z',
   'tweet_count': 3378},
  {'end': '2021-10-05T23:00:00.000Z',
   'start': '2021-10-05T22:00:00.000Z',
   'tweet_count': 3335},
  {'end': '2021-10-06T00:00:00.000Z',
   'start': '2021-10-05T23:00:00.000Z',
   'tweet_count': 3465},
  {'end': '2021-10-06T01:00:00.000Z',
   'start': '2021-10-06T00:00:00.000Z',
   'tweet_count': 2680},
  {'end': '2021-10-06T02:00:00.000Z',
   'start': '2021-10-06T01:00:00.000Z',
   'tweet_count': 2644},
  {'end': '2021-10-06T03:00:00.000Z',
   'start': '2021-10-06T02:00:00.000Z',
   'tweet_count': 2449},
  {'end': '2021-10-06T04:00:00.000Z',
   'start': '2021-10-06T03:00:00.000Z',
   'tweet_count': 2600},
  {'end': '2021-10-06T05:00:00.000Z',
   'start': '2021-10-06T04:00:00.000Z',
   'tweet_count': 2290},
  {'end': '2021-10-06T06:00:00.000Z',
   'start': '2021-10-06T05:00:00.000Z',
   'tweet_count': 2202},
  {'end': '2021-10-06T07:00:00.000Z',
   'start': '2021-10-06T06:00:00.000Z',
   'tweet_count': 2276},
  {'end': '2021-10-06T08:00:00.000Z',
   'start': '2021-10-06T07:00:00.000Z',
   'tweet_count': 2675},
  {'end': '2021-10-06T09:00:00.000Z',
   'start': '2021-10-06T08:00:00.000Z',
   'tweet_count': 2129},
  {'end': '2021-10-06T10:00:00.000Z',
   'start': '2021-10-06T09:00:00.000Z',
   'tweet_count': 1839},
  {'end': '2021-10-06T11:00:00.000Z',
   'start': '2021-10-06T10:00:00.000Z',
   'tweet_count': 2391},
  {'end': '2021-10-06T12:00:00.000Z',
   'start': '2021-10-06T11:00:00.000Z',
   'tweet_count': 2392},
  {'end': '2021-10-06T13:00:00.000Z',
   'start': '2021-10-06T12:00:00.000Z',
   'tweet_count': 2855},
  {'end': '2021-10-06T14:00:00.000Z',
   'start': '2021-10-06T13:00:00.000Z',
   'tweet_count': 3182},
  {'end': '2021-10-06T15:00:00.000Z',
   'start': '2021-10-06T14:00:00.000Z',
   'tweet_count': 3025},
  {'end': '2021-10-06T16:00:00.000Z',
   'start': '2021-10-06T15:00:00.000Z',
   'tweet_count': 3415},
  {'end': '2021-10-06T17:00:00.000Z',
   'start': '2021-10-06T16:00:00.000Z',
   'tweet_count': 3517},
  {'end': '2021-10-06T18:00:00.000Z',
   'start': '2021-10-06T17:00:00.000Z',
   'tweet_count': 3192},
  {'end': '2021-10-06T19:00:00.000Z',
   'start': '2021-10-06T18:00:00.000Z',
   'tweet_count': 2876},
  {'end': '2021-10-06T20:00:00.000Z',
   'start': '2021-10-06T19:00:00.000Z',
   'tweet_count': 2817},
  {'end': '2021-10-06T21:00:00.000Z',
   'start': '2021-10-06T20:00:00.000Z',
   'tweet_count': 3055},
  {'end': '2021-10-06T22:00:00.000Z',
   'start': '2021-10-06T21:00:00.000Z',
   'tweet_count': 2804},
  {'end': '2021-10-06T23:00:00.000Z',
   'start': '2021-10-06T22:00:00.000Z',
   'tweet_count': 2946},
  {'end': '2021-10-07T00:00:00.000Z',
   'start': '2021-10-06T23:00:00.000Z',
   'tweet_count': 2895},
  {'end': '2021-10-07T01:00:00.000Z',
   'start': '2021-10-07T00:00:00.000Z',
   'tweet_count': 2728},
  {'end': '2021-10-07T02:00:00.000Z',
   'start': '2021-10-07T01:00:00.000Z',
   'tweet_count': 2313},
  {'end': '2021-10-07T03:00:00.000Z',
   'start': '2021-10-07T02:00:00.000Z',
   'tweet_count': 1967},
  {'end': '2021-10-07T04:00:00.000Z',
   'start': '2021-10-07T03:00:00.000Z',
   'tweet_count': 2060},
  {'end': '2021-10-07T05:00:00.000Z',
   'start': '2021-10-07T04:00:00.000Z',
   'tweet_count': 1692},
  {'end': '2021-10-07T06:00:00.000Z',
   'start': '2021-10-07T05:00:00.000Z',
   'tweet_count': 1923},
  {'end': '2021-10-07T07:00:00.000Z',
   'start': '2021-10-07T06:00:00.000Z',
   'tweet_count': 2186},
  {'end': '2021-10-07T08:00:00.000Z',
   'start': '2021-10-07T07:00:00.000Z',
   'tweet_count': 2361},
  {'end': '2021-10-07T09:00:00.000Z',
   'start': '2021-10-07T08:00:00.000Z',
   'tweet_count': 2234},
  {'end': '2021-10-07T10:00:00.000Z',
   'start': '2021-10-07T09:00:00.000Z',
   'tweet_count': 2240},
  {'end': '2021-10-07T11:00:00.000Z',
   'start': '2021-10-07T10:00:00.000Z',
   'tweet_count': 2505},
  {'end': '2021-10-07T12:00:00.000Z',
   'start': '2021-10-07T11:00:00.000Z',
   'tweet_count': 2533},
  {'end': '2021-10-07T13:00:00.000Z',
   'start': '2021-10-07T12:00:00.000Z',
   'tweet_count': 3062},
  {'end': '2021-10-07T14:00:00.000Z',
   'start': '2021-10-07T13:00:00.000Z',
   'tweet_count': 2800},
  {'end': '2021-10-07T15:00:00.000Z',
   'start': '2021-10-07T14:00:00.000Z',
   'tweet_count': 2828},
  {'end': '2021-10-07T16:00:00.000Z',
   'start': '2021-10-07T15:00:00.000Z',
   'tweet_count': 2773},
  {'end': '2021-10-07T17:00:00.000Z',
   'start': '2021-10-07T16:00:00.000Z',
   'tweet_count': 2721},
  {'end': '2021-10-07T18:00:00.000Z',
   'start': '2021-10-07T17:00:00.000Z',
   'tweet_count': 2640},
  {'end': '2021-10-07T19:00:00.000Z',
   'start': '2021-10-07T18:00:00.000Z',
   'tweet_count': 2941},
  {'end': '2021-10-07T20:00:00.000Z',
   'start': '2021-10-07T19:00:00.000Z',
   'tweet_count': 2978},
  {'end': '2021-10-07T21:00:00.000Z',
   'start': '2021-10-07T20:00:00.000Z',
   'tweet_count': 2419},
  {'end': '2021-10-07T22:00:00.000Z',
   'start': '2021-10-07T21:00:00.000Z',
   'tweet_count': 2748},
  {'end': '2021-10-07T23:00:00.000Z',
   'start': '2021-10-07T22:00:00.000Z',
   'tweet_count': 2692},
  {'end': '2021-10-08T00:00:00.000Z',
   'start': '2021-10-07T23:00:00.000Z',
   'tweet_count': 2339},
  {'end': '2021-10-08T01:00:00.000Z',
   'start': '2021-10-08T00:00:00.000Z',
   'tweet_count': 2157},
  {'end': '2021-10-08T02:00:00.000Z',
   'start': '2021-10-08T01:00:00.000Z',
   'tweet_count': 1866},
  {'end': '2021-10-08T03:00:00.000Z',
   'start': '2021-10-08T02:00:00.000Z',
   'tweet_count': 1886},
  {'end': '2021-10-08T04:00:00.000Z',
   'start': '2021-10-08T03:00:00.000Z',
   'tweet_count': 2865},
  {'end': '2021-10-08T05:00:00.000Z',
   'start': '2021-10-08T04:00:00.000Z',
   'tweet_count': 1979},
  {'end': '2021-10-08T06:00:00.000Z',
   'start': '2021-10-08T05:00:00.000Z',
   'tweet_count': 2041},
  {'end': '2021-10-08T07:00:00.000Z',
   'start': '2021-10-08T06:00:00.000Z',
   'tweet_count': 1894},
  {'end': '2021-10-08T08:00:00.000Z',
   'start': '2021-10-08T07:00:00.000Z',
   'tweet_count': 1988},
  {'end': '2021-10-08T09:00:00.000Z',
   'start': '2021-10-08T08:00:00.000Z',
   'tweet_count': 2117},
  {'end': '2021-10-08T10:00:00.000Z',
   'start': '2021-10-08T09:00:00.000Z',
   'tweet_count': 2514},
  {'end': '2021-10-08T11:00:00.000Z',
   'start': '2021-10-08T10:00:00.000Z',
   'tweet_count': 2357},
  {'end': '2021-10-08T12:00:00.000Z',
   'start': '2021-10-08T11:00:00.000Z',
   'tweet_count': 2235},
  {'end': '2021-10-08T13:00:00.000Z',
   'start': '2021-10-08T12:00:00.000Z',
   'tweet_count': 2802},
  {'end': '2021-10-08T14:00:00.000Z',
   'start': '2021-10-08T13:00:00.000Z',
   'tweet_count': 3274},
  {'end': '2021-10-08T15:00:00.000Z',
   'start': '2021-10-08T14:00:00.000Z',
   'tweet_count': 2963},
  {'end': '2021-10-08T16:00:00.000Z',
   'start': '2021-10-08T15:00:00.000Z',
   'tweet_count': 2736},
  {'end': '2021-10-08T17:00:00.000Z',
   'start': '2021-10-08T16:00:00.000Z',
   'tweet_count': 2579},
  {'end': '2021-10-08T18:00:00.000Z',
   'start': '2021-10-08T17:00:00.000Z',
   'tweet_count': 2376},
  {'end': '2021-10-08T19:00:00.000Z',
   'start': '2021-10-08T18:00:00.000Z',
   'tweet_count': 2840},
  {'end': '2021-10-08T20:00:00.000Z',
   'start': '2021-10-08T19:00:00.000Z',
   'tweet_count': 2685},
  {'end': '2021-10-08T21:00:00.000Z',
   'start': '2021-10-08T20:00:00.000Z',
   'tweet_count': 2227},
  {'end': '2021-10-08T22:00:00.000Z',
   'start': '2021-10-08T21:00:00.000Z',
   'tweet_count': 2137},
  {'end': '2021-10-08T23:00:00.000Z',
   'start': '2021-10-08T22:00:00.000Z',
   'tweet_count': 2053},
  {'end': '2021-10-09T00:00:00.000Z',
   'start': '2021-10-08T23:00:00.000Z',
   'tweet_count': 1914},
  {'end': '2021-10-09T01:00:00.000Z',
   'start': '2021-10-09T00:00:00.000Z',
   'tweet_count': 2231},
  {'end': '2021-10-09T02:00:00.000Z',
   'start': '2021-10-09T01:00:00.000Z',
   'tweet_count': 1884},
  {'end': '2021-10-09T03:00:00.000Z',
   'start': '2021-10-09T02:00:00.000Z',
   'tweet_count': 1815},
  {'end': '2021-10-09T04:00:00.000Z',
   'start': '2021-10-09T03:00:00.000Z',
   'tweet_count': 2010},
  {'end': '2021-10-09T05:00:00.000Z',
   'start': '2021-10-09T04:00:00.000Z',
   'tweet_count': 1704},
  {'end': '2021-10-09T06:00:00.000Z',
   'start': '2021-10-09T05:00:00.000Z',
   'tweet_count': 1518},
  {'end': '2021-10-09T07:00:00.000Z',
   'start': '2021-10-09T06:00:00.000Z',
   'tweet_count': 1687},
  {'end': '2021-10-09T08:00:00.000Z',
   'start': '2021-10-09T07:00:00.000Z',
   'tweet_count': 2081},
  {'end': '2021-10-09T09:00:00.000Z',
   'start': '2021-10-09T08:00:00.000Z',
   'tweet_count': 1789},
  {'end': '2021-10-09T10:00:00.000Z',
   'start': '2021-10-09T09:00:00.000Z',
   'tweet_count': 1794},
  {'end': '2021-10-09T11:00:00.000Z',
   'start': '2021-10-09T10:00:00.000Z',
   'tweet_count': 2360},
  {'end': '2021-10-09T12:00:00.000Z',
   'start': '2021-10-09T11:00:00.000Z',
   'tweet_count': 3125},
  {'end': '2021-10-09T13:00:00.000Z',
   'start': '2021-10-09T12:00:00.000Z',
   'tweet_count': 2709},
  {'end': '2021-10-09T14:00:00.000Z',
   'start': '2021-10-09T13:00:00.000Z',
   'tweet_count': 3010},
  {'end': '2021-10-09T15:00:00.000Z',
   'start': '2021-10-09T14:00:00.000Z',
   'tweet_count': 3366},
  {'end': '2021-10-09T16:00:00.000Z',
   'start': '2021-10-09T15:00:00.000Z',
   'tweet_count': 3776},
  {'end': '2021-10-09T17:00:00.000Z',
   'start': '2021-10-09T16:00:00.000Z',
   'tweet_count': 5707},
  {'end': '2021-10-09T18:00:00.000Z',
   'start': '2021-10-09T17:00:00.000Z',
   'tweet_count': 4237},
  {'end': '2021-10-09T19:00:00.000Z',
   'start': '2021-10-09T18:00:00.000Z',
   'tweet_count': 3070},
  {'end': '2021-10-09T20:00:00.000Z',
   'start': '2021-10-09T19:00:00.000Z',
   'tweet_count': 2861},
  {'end': '2021-10-09T21:00:00.000Z',
   'start': '2021-10-09T20:00:00.000Z',
   'tweet_count': 2602},
  {'end': '2021-10-09T22:00:00.000Z',
   'start': '2021-10-09T21:00:00.000Z',
   'tweet_count': 2764},
  {'end': '2021-10-09T22:26:13.000Z',
   'start': '2021-10-09T22:00:00.000Z',
   'tweet_count': 1121}],
 'meta': {'total_tweet_count': 418743}}

In [38]:
xrp_tweet_count_df = pd.DataFrame.from_dict(data["data"])

In [39]:
xrp_tweet_count_df.head()

                        end                     start  tweet_count
0  2021-10-02T23:00:00.000Z  2021-10-02T22:26:13.000Z          844
1  2021-10-03T00:00:00.000Z  2021-10-02T23:00:00.000Z         1614
2  2021-10-03T01:00:00.000Z  2021-10-03T00:00:00.000Z         1473
3  2021-10-03T02:00:00.000Z  2021-10-03T01:00:00.000Z         1342
4  2021-10-03T03:00:00.000Z  2021-10-03T02:00:00.000Z         1343

In [40]:
xrp_tweet_count_df["end"] = pd.to_datetime(xrp_tweet_count_df["end"])

In [41]:
xrp_tweet_count_df["start"] = pd.to_datetime(xrp_tweet_count_df["start"])

In [42]:
xrp_tweet_count_df.head()

                        end                     start  tweet_count
0 2021-10-02 23:00:00+00:00 2021-10-02 22:26:13+00:00          844
1 2021-10-03 00:00:00+00:00 2021-10-02 23:00:00+00:00         1614
2 2021-10-03 01:00:00+00:00 2021-10-03 00:00:00+00:00         1473
3 2021-10-03 02:00:00+00:00 2021-10-03 01:00:00+00:00         1342
4 2021-10-03 03:00:00+00:00 2021-10-03 02:00:00+00:00         1343

In [43]:
xrp_tweet_count_df = xrp_tweet_count_df.rename(columns={"end" : "Timestamp"})

In [44]:
xrp_tweet_count_df.head()

                  Timestamp                     start  tweet_count
0 2021-10-02 23:00:00+00:00 2021-10-02 22:26:13+00:00          844
1 2021-10-03 00:00:00+00:00 2021-10-02 23:00:00+00:00         1614
2 2021-10-03 01:00:00+00:00 2021-10-03 00:00:00+00:00         1473
3 2021-10-03 02:00:00+00:00 2021-10-03 01:00:00+00:00         1342
4 2021-10-03 03:00:00+00:00 2021-10-03 02:00:00+00:00         1343

In [45]:
xrp_tweet_count_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 169 entries, 0 to 168
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Timestamp    169 non-null    datetime64[ns, UTC]
 1   start        169 non-null    datetime64[ns, UTC]
 2   tweet_count  169 non-null    int64
dtypes: datetime64[ns, UTC](2), int64(1)
memory usage: 4.1 KB

In [46]:
engine = create_engine("sqlite:///xrp_tweet_count_df.db", echo=True)
sqlite_connection = engine.connect()

In [47]:
sqlite_table = "xrp_tweet_count_df3"
xrp_tweet_count_df.to_sql(sqlite_table, sqlite_connection, if_exists="fail")

2021-10-09 15:44:27,644 INFO sqlalchemy.engine.Engine PRAGMA main.table_info("xrp_tweet_count_df3")
2021-10-09 15:44:27,645 INFO sqlalchemy.engine.Engine [raw sql] ()
2021-10-09 15:44:27,647 INFO sqlalchemy.engine.Engine PRAGMA temp.table_info("xrp_tweet_count_df3")
2021-10-09 15:44:27,647 INFO sqlalchemy.engine.Engine [raw sql] ()
2021-10-09 15:44:27,650 INFO sqlalchemy.engine.Engine
CREATE TABLE xrp_tweet_count_df3 (
	"index" BIGINT,
	"Timestamp" TIMESTAMP,
	start TIMESTAMP,
	tweet_count BIGINT
)


2021-10-09 15:44:27,651 INFO sqlalchemy.engine.Engine [no key 0.00084s] ()
2021-10-09 15:44:27,657 INFO sqlalchemy.engine.Engine COMMIT
2021-10-09 15:44:27,657 INFO sqlalchemy.engine.Engine CREATE INDEX ix_xrp_tweet_count_df3_index ON xrp_tweet_count_df3 ("index")
2021-10-09 15:44:27,658 INFO sqlalchemy.engine.Engine [no key 0.00060s] ()
2021-10-09 15:44:27,665 INFO sqlalchemy.engine.Engine COMMIT
2021-10-09 15:44:27,668 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2021-10-09 15:44:27,671 INFO sqlalchemy.engine.Engine INSERT INTO xrp_tweet_count_df3 ("index", "Timestamp", start, tweet_count) VALUES (?, ?, ?, ?)
2021-10-09 15:44:27,672 INFO sqlalchemy.engine.Engine [generated in 0.00279s] ((0, '2021-10-02 23:00:00.000000', '2021-10-02 22:26:13.000000', 844), (1, '2021-10-03 00:00:00.000000', '2021-10-02 23:00:00.000000', 1614), (2, '2021-10-03 01:00:00.000000', '2021-10-03 00:00:00.000000', 1473), (3, '2021-10-03 02:00:00.000000', '2021-10-03 01:00:00.000000', 1342), (4, '2021-10-03 03:00:00.000000', '2021-10-03 02:00:00.000000', 1343), (5, '2021-10-03 04:00:00.000000', '2021-10-03 03:00:00.000000', 1314), (6, '2021-10-03 05:00:00.000000', '2021-10-03 04:00:00.000000', 1241), (7, '2021-10-03 06:00:00.000000', '2021-10-03 05:00:00.000000', 1293)  ... displaying 10 of 169 total bound parameter sets ...  (167, '2021-10-09 22:00:00.000000', '2021-10-09 21:00:00.000000', 2764), (168, '2021-10-09 22:26:13.000000', '2021-10-09 22:00:00.000000', 1121))
2021-10-09 15:44:27,674 INFO sqlalchemy.engine.Engine COMMIT