In [48]:
from pathlib import Path
import json
import pandas as pd
import sqlalchemy as sql
from sqlalchemy import create_engine
from time import gmtime, strftime
import time

In [49]:
with open(Path("BNB_tweet_count.json")) as f:
    data = json.load(f)

In [50]:
data

{'data': [{'end': '2021-10-02T23:00:00.000Z',
   'start': '2021-10-02T22:51:04.000Z',
   'tweet_count': 829},
  {'end': '2021-10-03T00:00:00.000Z',
   'start': '2021-10-02T23:00:00.000Z',
   'tweet_count': 5932},
  {'end': '2021-10-03T01:00:00.000Z',
   'start': '2021-10-03T00:00:00.000Z',
   'tweet_count': 6084},
  {'end': '2021-10-03T02:00:00.000Z',
   'start': '2021-10-03T01:00:00.000Z',
   'tweet_count': 7327},
  {'end': '2021-10-03T03:00:00.000Z',
   'start': '2021-10-03T02:00:00.000Z',
   'tweet_count': 8929},
  {'end': '2021-10-03T04:00:00.000Z',
   'start': '2021-10-03T03:00:00.000Z',
   'tweet_count': 7509},
  {'end': '2021-10-03T05:00:00.000Z',
   'start': '2021-10-03T04:00:00.000Z',
   'tweet_count': 6820},
  {'end': '2021-10-03T06:00:00.000Z',
   'start': '2021-10-03T05:00:00.000Z',
   'tweet_count': 10235},
  {'end': '2021-10-03T07:00:00.000Z',
   'start': '2021-10-03T06:00:00.000Z',
   'tweet_count': 27012},
  {'end': '2021-10-03T08:00:00.000Z',
   'start': '2021-10-03T07:00:00.000Z',
   'tweet_count': 8261},
  {'end': '2021-10-03T09:00:00.000Z',
   'start': '2021-10-03T08:00:00.000Z',
   'tweet_count': 9064},
  {'end': '2021-10-03T10:00:00.000Z',
   'start': '2021-10-03T09:00:00.000Z',
   'tweet_count': 8450},
  {'end': '2021-10-03T11:00:00.000Z',
   'start': '2021-10-03T10:00:00.000Z',
   'tweet_count': 8844},
  {'end': '2021-10-03T12:00:00.000Z',
   'start': '2021-10-03T11:00:00.000Z',
   'tweet_count': 9926},
  {'end': '2021-10-03T13:00:00.000Z',
   'start': '2021-10-03T12:00:00.000Z',
   'tweet_count': 9162},
  {'end': '2021-10-03T14:00:00.000Z',
   'start': '2021-10-03T13:00:00.000Z',
   'tweet_count': 9658},
  {'end': '2021-10-03T15:00:00.000Z',
   'start': '2021-10-03T14:00:00.000Z',
   'tweet_count': 9507},
  {'end': '2021-10-03T16:00:00.000Z',
   'start': '2021-10-03T15:00:00.000Z',
   'tweet_count': 10325},
  {'end': '2021-10-03T17:00:00.000Z',
   'start': '2021-10-03T16:00:00.000Z',
   'tweet_count': 9213},
  {'end': '2021-10-03T18:00:00.000Z',
   'start': '2021-10-03T17:00:00.000Z',
   'tweet_count': 8061},
  {'end': '2021-10-03T19:00:00.000Z',
   'start': '2021-10-03T18:00:00.000Z',
   'tweet_count': 7004},
  {'end': '2021-10-03T20:00:00.000Z',
   'start': '2021-10-03T19:00:00.000Z',
   'tweet_count': 7388},
  {'end': '2021-10-03T21:00:00.000Z',
   'start': '2021-10-03T20:00:00.000Z',
   'tweet_count': 5670},
  {'end': '2021-10-03T22:00:00.000Z',
   'start': '2021-10-03T21:00:00.000Z',
   'tweet_count': 4076},
  {'end': '2021-10-03T23:00:00.000Z',
   'start': '2021-10-03T22:00:00.000Z',
   'tweet_count': 4067},
  {'end': '2021-10-04T00:00:00.000Z',
   'start': '2021-10-03T23:00:00.000Z',
   'tweet_count': 4483},
  {'end': '2021-10-04T01:00:00.000Z',
   'start': '2021-10-04T00:00:00.000Z',
   'tweet_count': 5278},
  {'end': '2021-10-04T02:00:00.000Z',
   'start': '2021-10-04T01:00:00.000Z',
   'tweet_count': 4910},
  {'end': '2021-10-04T03:00:00.000Z',
   'start': '2021-10-04T02:00:00.000Z',
   'tweet_count': 7076},
  {'end': '2021-10-04T04:00:00.000Z',
   'start': '2021-10-04T03:00:00.000Z',
   'tweet_count': 6722},
  {'end': '2021-10-04T05:00:00.000Z',
   'start': '2021-10-04T04:00:00.000Z',
   'tweet_count': 6422},
  {'end': '2021-10-04T06:00:00.000Z',
   'start': '2021-10-04T05:00:00.000Z',
   'tweet_count': 6765},
  {'end': '2021-10-04T07:00:00.000Z',
   'start': '2021-10-04T06:00:00.000Z',
   'tweet_count': 8137},
  {'end': '2021-10-04T08:00:00.000Z',
   'start': '2021-10-04T07:00:00.000Z',
   'tweet_count': 7787},
  {'end': '2021-10-04T09:00:00.000Z',
   'start': '2021-10-04T08:00:00.000Z',
   'tweet_count': 6807},
  {'end': '2021-10-04T10:00:00.000Z',
   'start': '2021-10-04T09:00:00.000Z',
   'tweet_count': 6605},
  {'end': '2021-10-04T11:00:00.000Z',
   'start': '2021-10-04T10:00:00.000Z',
   'tweet_count': 6530},
  {'end': '2021-10-04T12:00:00.000Z',
   'start': '2021-10-04T11:00:00.000Z',
   'tweet_count': 7022},
  {'end': '2021-10-04T13:00:00.000Z',
   'start': '2021-10-04T12:00:00.000Z',
   'tweet_count': 8576},
  {'end': '2021-10-04T14:00:00.000Z',
   'start': '2021-10-04T13:00:00.000Z',
   'tweet_count': 8359},
  {'end': '2021-10-04T15:00:00.000Z',
   'start': '2021-10-04T14:00:00.000Z',
   'tweet_count': 11073},
  {'end': '2021-10-04T16:00:00.000Z',
   'start': '2021-10-04T15:00:00.000Z',
   'tweet_count': 10320},
  {'end': '2021-10-04T17:00:00.000Z',
   'start': '2021-10-04T16:00:00.000Z',
   'tweet_count': 8860},
  {'end': '2021-10-04T18:00:00.000Z',
   'start': '2021-10-04T17:00:00.000Z',
   'tweet_count': 6607},
  {'end': '2021-10-04T19:00:00.000Z',
   'start': '2021-10-04T18:00:00.000Z',
   'tweet_count': 5724},
  {'end': '2021-10-04T20:00:00.000Z',
   'start': '2021-10-04T19:00:00.000Z',
   'tweet_count': 5115},
  {'end': '2021-10-04T21:00:00.000Z',
   'start': '2021-10-04T20:00:00.000Z',
   'tweet_count': 4477},
  {'end': '2021-10-04T22:00:00.000Z',
   'start': '2021-10-04T21:00:00.000Z',
   'tweet_count': 3527},
  {'end': '2021-10-04T23:00:00.000Z',
   'start': '2021-10-04T22:00:00.000Z',
   'tweet_count': 3722},
  {'end': '2021-10-05T00:00:00.000Z',
   'start': '2021-10-04T23:00:00.000Z',
   'tweet_count': 3853},
  {'end': '2021-10-05T01:00:00.000Z',
   'start': '2021-10-05T00:00:00.000Z',
   'tweet_count': 3867},
  {'end': '2021-10-05T02:00:00.000Z',
   'start': '2021-10-05T01:00:00.000Z',
   'tweet_count': 4708},
  {'end': '2021-10-05T03:00:00.000Z',
   'start': '2021-10-05T02:00:00.000Z',
   'tweet_count': 5751},
  {'end': '2021-10-05T04:00:00.000Z',
   'start': '2021-10-05T03:00:00.000Z',
   'tweet_count': 5130},
  {'end': '2021-10-05T05:00:00.000Z',
   'start': '2021-10-05T04:00:00.000Z',
   'tweet_count': 5475},
  {'end': '2021-10-05T06:00:00.000Z',
   'start': '2021-10-05T05:00:00.000Z',
   'tweet_count': 7200},
  {'end': '2021-10-05T07:00:00.000Z',
   'start': '2021-10-05T06:00:00.000Z',
   'tweet_count': 6385},
  {'end': '2021-10-05T08:00:00.000Z',
   'start': '2021-10-05T07:00:00.000Z',
   'tweet_count': 6241},
  {'end': '2021-10-05T09:00:00.000Z',
   'start': '2021-10-05T08:00:00.000Z',
   'tweet_count': 6034},
  {'end': '2021-10-05T10:00:00.000Z',
   'start': '2021-10-05T09:00:00.000Z',
   'tweet_count': 5804},
  {'end': '2021-10-05T11:00:00.000Z',
   'start': '2021-10-05T10:00:00.000Z',
   'tweet_count': 5493},
  {'end': '2021-10-05T12:00:00.000Z',
   'start': '2021-10-05T11:00:00.000Z',
   'tweet_count': 7055},
  {'end': '2021-10-05T13:00:00.000Z',
   'start': '2021-10-05T12:00:00.000Z',
   'tweet_count': 6873},
  {'end': '2021-10-05T14:00:00.000Z',
   'start': '2021-10-05T13:00:00.000Z',
   'tweet_count': 7853},
  {'end': '2021-10-05T15:00:00.000Z',
   'start': '2021-10-05T14:00:00.000Z',
   'tweet_count': 8193},
  {'end': '2021-10-05T16:00:00.000Z',
   'start': '2021-10-05T15:00:00.000Z',
   'tweet_count': 8106},
  {'end': '2021-10-05T17:00:00.000Z',
   'start': '2021-10-05T16:00:00.000Z',
   'tweet_count': 6829},
  {'end': '2021-10-05T18:00:00.000Z',
   'start': '2021-10-05T17:00:00.000Z',
   'tweet_count': 7250},
  {'end': '2021-10-05T19:00:00.000Z',
   'start': '2021-10-05T18:00:00.000Z',
   'tweet_count': 6407},
  {'end': '2021-10-05T20:00:00.000Z',
   'start': '2021-10-05T19:00:00.000Z',
   'tweet_count': 6338},
  {'end': '2021-10-05T21:00:00.000Z',
   'start': '2021-10-05T20:00:00.000Z',
   'tweet_count': 5753},
  {'end': '2021-10-05T22:00:00.000Z',
   'start': '2021-10-05T21:00:00.000Z',
   'tweet_count': 4910},
  {'end': '2021-10-05T23:00:00.000Z',
   'start': '2021-10-05T22:00:00.000Z',
   'tweet_count': 4865},
  {'end': '2021-10-06T00:00:00.000Z',
   'start': '2021-10-05T23:00:00.000Z',
   'tweet_count': 6005},
  {'end': '2021-10-06T01:00:00.000Z',
   'start': '2021-10-06T00:00:00.000Z',
   'tweet_count': 6188},
  {'end': '2021-10-06T02:00:00.000Z',
   'start': '2021-10-06T01:00:00.000Z',
   'tweet_count': 5794},
  {'end': '2021-10-06T03:00:00.000Z',
   'start': '2021-10-06T02:00:00.000Z',
   'tweet_count': 6813},
  {'end': '2021-10-06T04:00:00.000Z',
   'start': '2021-10-06T03:00:00.000Z',
   'tweet_count': 6448},
  {'end': '2021-10-06T05:00:00.000Z',
   'start': '2021-10-06T04:00:00.000Z',
   'tweet_count': 7126},
  {'end': '2021-10-06T06:00:00.000Z',
   'start': '2021-10-06T05:00:00.000Z',
   'tweet_count': 8120},
  {'end': '2021-10-06T07:00:00.000Z',
   'start': '2021-10-06T06:00:00.000Z',
   'tweet_count': 8842},
  {'end': '2021-10-06T08:00:00.000Z',
   'start': '2021-10-06T07:00:00.000Z',
   'tweet_count': 10478},
  {'end': '2021-10-06T09:00:00.000Z',
   'start': '2021-10-06T08:00:00.000Z',
   'tweet_count': 12413},
  {'end': '2021-10-06T10:00:00.000Z',
   'start': '2021-10-06T09:00:00.000Z',
   'tweet_count': 12828},
  {'end': '2021-10-06T11:00:00.000Z',
   'start': '2021-10-06T10:00:00.000Z',
   'tweet_count': 10919},
  {'end': '2021-10-06T12:00:00.000Z',
   'start': '2021-10-06T11:00:00.000Z',
   'tweet_count': 8618},
  {'end': '2021-10-06T13:00:00.000Z',
   'start': '2021-10-06T12:00:00.000Z',
   'tweet_count': 11789},
  {'end': '2021-10-06T14:00:00.000Z',
   'start': '2021-10-06T13:00:00.000Z',
   'tweet_count': 11832},
  {'end': '2021-10-06T15:00:00.000Z',
   'start': '2021-10-06T14:00:00.000Z',
   'tweet_count': 9923},
  {'end': '2021-10-06T16:00:00.000Z',
   'start': '2021-10-06T15:00:00.000Z',
   'tweet_count': 10986},
  {'end': '2021-10-06T17:00:00.000Z',
   'start': '2021-10-06T16:00:00.000Z',
   'tweet_count': 8583},
  {'end': '2021-10-06T18:00:00.000Z',
   'start': '2021-10-06T17:00:00.000Z',
   'tweet_count': 7060},
  {'end': '2021-10-06T19:00:00.000Z',
   'start': '2021-10-06T18:00:00.000Z',
   'tweet_count': 6848},
  {'end': '2021-10-06T20:00:00.000Z',
   'start': '2021-10-06T19:00:00.000Z',
   'tweet_count': 6151},
  {'end': '2021-10-06T21:00:00.000Z',
   'start': '2021-10-06T20:00:00.000Z',
   'tweet_count': 5022},
  {'end': '2021-10-06T22:00:00.000Z',
   'start': '2021-10-06T21:00:00.000Z',
   'tweet_count': 4472},
  {'end': '2021-10-06T23:00:00.000Z',
   'start': '2021-10-06T22:00:00.000Z',
   'tweet_count': 4779},
  {'end': '2021-10-07T00:00:00.000Z',
   'start': '2021-10-06T23:00:00.000Z',
   'tweet_count': 7221},
  {'end': '2021-10-07T01:00:00.000Z',
   'start': '2021-10-07T00:00:00.000Z',
   'tweet_count': 5077},
  {'end': '2021-10-07T02:00:00.000Z',
   'start': '2021-10-07T01:00:00.000Z',
   'tweet_count': 6112},
  {'end': '2021-10-07T03:00:00.000Z',
   'start': '2021-10-07T02:00:00.000Z',
   'tweet_count': 5785},
  {'end': '2021-10-07T04:00:00.000Z',
   'start': '2021-10-07T03:00:00.000Z',
   'tweet_count': 5682},
  {'end': '2021-10-07T05:00:00.000Z',
   'start': '2021-10-07T04:00:00.000Z',
   'tweet_count': 6477},
  {'end': '2021-10-07T06:00:00.000Z',
   'start': '2021-10-07T05:00:00.000Z',
   'tweet_count': 5722},
  {'end': '2021-10-07T07:00:00.000Z',
   'start': '2021-10-07T06:00:00.000Z',
   'tweet_count': 5996},
  {'end': '2021-10-07T08:00:00.000Z',
   'start': '2021-10-07T07:00:00.000Z',
   'tweet_count': 6264},
  {'end': '2021-10-07T09:00:00.000Z',
   'start': '2021-10-07T08:00:00.000Z',
   'tweet_count': 6842},
  {'end': '2021-10-07T10:00:00.000Z',
   'start': '2021-10-07T09:00:00.000Z',
   'tweet_count': 9155},
  {'end': '2021-10-07T11:00:00.000Z',
   'start': '2021-10-07T10:00:00.000Z',
   'tweet_count': 8513},
  {'end': '2021-10-07T12:00:00.000Z',
   'start': '2021-10-07T11:00:00.000Z',
   'tweet_count': 8951},
  {'end': '2021-10-07T13:00:00.000Z',
   'start': '2021-10-07T12:00:00.000Z',
   'tweet_count': 9631},
  {'end': '2021-10-07T14:00:00.000Z',
   'start': '2021-10-07T13:00:00.000Z',
   'tweet_count': 7440},
  {'end': '2021-10-07T15:00:00.000Z',
   'start': '2021-10-07T14:00:00.000Z',
   'tweet_count': 9867},
  {'end': '2021-10-07T16:00:00.000Z',
   'start': '2021-10-07T15:00:00.000Z',
   'tweet_count': 9027},
  {'end': '2021-10-07T17:00:00.000Z',
   'start': '2021-10-07T16:00:00.000Z',
   'tweet_count': 8418},
  {'end': '2021-10-07T18:00:00.000Z',
   'start': '2021-10-07T17:00:00.000Z',
   'tweet_count': 7352},
  {'end': '2021-10-07T19:00:00.000Z',
   'start': '2021-10-07T18:00:00.000Z',
   'tweet_count': 6027},
  {'end': '2021-10-07T20:00:00.000Z',
   'start': '2021-10-07T19:00:00.000Z',
   'tweet_count': 6042},
  {'end': '2021-10-07T21:00:00.000Z',
   'start': '2021-10-07T20:00:00.000Z',
   'tweet_count': 6283},
  {'end': '2021-10-07T22:00:00.000Z',
   'start': '2021-10-07T21:00:00.000Z',
   'tweet_count': 5186},
  {'end': '2021-10-07T23:00:00.000Z',
   'start': '2021-10-07T22:00:00.000Z',
   'tweet_count': 4660},
  {'end': '2021-10-08T00:00:00.000Z',
   'start': '2021-10-07T23:00:00.000Z',
   'tweet_count': 5430},
  {'end': '2021-10-08T01:00:00.000Z',
   'start': '2021-10-08T00:00:00.000Z',
   'tweet_count': 4621},
  {'end': '2021-10-08T02:00:00.000Z',
   'start': '2021-10-08T01:00:00.000Z',
   'tweet_count': 5646},
  {'end': '2021-10-08T03:00:00.000Z',
   'start': '2021-10-08T02:00:00.000Z',
   'tweet_count': 5299},
  {'end': '2021-10-08T04:00:00.000Z',
   'start': '2021-10-08T03:00:00.000Z',
   'tweet_count': 6904},
  {'end': '2021-10-08T05:00:00.000Z',
   'start': '2021-10-08T04:00:00.000Z',
   'tweet_count': 7279},
  {'end': '2021-10-08T06:00:00.000Z',
   'start': '2021-10-08T05:00:00.000Z',
   'tweet_count': 7007},
  {'end': '2021-10-08T07:00:00.000Z',
   'start': '2021-10-08T06:00:00.000Z',
   'tweet_count': 6700},
  {'end': '2021-10-08T08:00:00.000Z',
   'start': '2021-10-08T07:00:00.000Z',
   'tweet_count': 6017},
  {'end': '2021-10-08T09:00:00.000Z',
   'start': '2021-10-08T08:00:00.000Z',
   'tweet_count': 7366},
  {'end': '2021-10-08T10:00:00.000Z',
   'start': '2021-10-08T09:00:00.000Z',
   'tweet_count': 9236},
  {'end': '2021-10-08T11:00:00.000Z',
   'start': '2021-10-08T10:00:00.000Z',
   'tweet_count': 9538},
  {'end': '2021-10-08T12:00:00.000Z',
   'start': '2021-10-08T11:00:00.000Z',
   'tweet_count': 7705},
  {'end': '2021-10-08T13:00:00.000Z',
   'start': '2021-10-08T12:00:00.000Z',
   'tweet_count': 9116},
  {'end': '2021-10-08T14:00:00.000Z',
   'start': '2021-10-08T13:00:00.000Z',
   'tweet_count': 10031},
  {'end': '2021-10-08T15:00:00.000Z',
   'start': '2021-10-08T14:00:00.000Z',
   'tweet_count': 8701},
  {'end': '2021-10-08T16:00:00.000Z',
   'start': '2021-10-08T15:00:00.000Z',
   'tweet_count': 10756},
  {'end': '2021-10-08T17:00:00.000Z',
   'start': '2021-10-08T16:00:00.000Z',
   'tweet_count': 10804},
  {'end': '2021-10-08T18:00:00.000Z',
   'start': '2021-10-08T17:00:00.000Z',
   'tweet_count': 10073},
  {'end': '2021-10-08T19:00:00.000Z',
   'start': '2021-10-08T18:00:00.000Z',
   'tweet_count': 7633},
  {'end': '2021-10-08T20:00:00.000Z',
   'start': '2021-10-08T19:00:00.000Z',
   'tweet_count': 7039},
  {'end': '2021-10-08T21:00:00.000Z',
   'start': '2021-10-08T20:00:00.000Z',
   'tweet_count': 6783},
  {'end': '2021-10-08T22:00:00.000Z',
   'start': '2021-10-08T21:00:00.000Z',
   'tweet_count': 5312},
  {'end': '2021-10-08T23:00:00.000Z',
   'start': '2021-10-08T22:00:00.000Z',
   'tweet_count': 5903},
  {'end': '2021-10-09T00:00:00.000Z',
   'start': '2021-10-08T23:00:00.000Z',
   'tweet_count': 6699},
  {'end': '2021-10-09T01:00:00.000Z',
   'start': '2021-10-09T00:00:00.000Z',
   'tweet_count': 6826},
  {'end': '2021-10-09T02:00:00.000Z',
   'start': '2021-10-09T01:00:00.000Z',
   'tweet_count': 6362},
  {'end': '2021-10-09T03:00:00.000Z',
   'start': '2021-10-09T02:00:00.000Z',
   'tweet_count': 6081},
  {'end': '2021-10-09T04:00:00.000Z',
   'start': '2021-10-09T03:00:00.000Z',
   'tweet_count': 7678},
  {'end': '2021-10-09T05:00:00.000Z',
   'start': '2021-10-09T04:00:00.000Z',
   'tweet_count': 7397},
  {'end': '2021-10-09T06:00:00.000Z',
   'start': '2021-10-09T05:00:00.000Z',
   'tweet_count': 7576},
  {'end': '2021-10-09T07:00:00.000Z',
   'start': '2021-10-09T06:00:00.000Z',
   'tweet_count': 10285},
  {'end': '2021-10-09T08:00:00.000Z',
   'start': '2021-10-09T07:00:00.000Z',
   'tweet_count': 10245},
  {'end': '2021-10-09T09:00:00.000Z',
   'start': '2021-10-09T08:00:00.000Z',
   'tweet_count': 10145},
  {'end': '2021-10-09T10:00:00.000Z',
   'start': '2021-10-09T09:00:00.000Z',
   'tweet_count': 10090},
  {'end': '2021-10-09T11:00:00.000Z',
   'start': '2021-10-09T10:00:00.000Z',
   'tweet_count': 7894},
  {'end': '2021-10-09T12:00:00.000Z',
   'start': '2021-10-09T11:00:00.000Z',
   'tweet_count': 8274},
  {'end': '2021-10-09T13:00:00.000Z',
   'start': '2021-10-09T12:00:00.000Z',
   'tweet_count': 11077},
  {'end': '2021-10-09T14:00:00.000Z',
   'start': '2021-10-09T13:00:00.000Z',
   'tweet_count': 11125},
  {'end': '2021-10-09T15:00:00.000Z',
   'start': '2021-10-09T14:00:00.000Z',
   'tweet_count': 10197},
  {'end': '2021-10-09T16:00:00.000Z',
   'start': '2021-10-09T15:00:00.000Z',
   'tweet_count': 10066},
  {'end': '2021-10-09T17:00:00.000Z',
   'start': '2021-10-09T16:00:00.000Z',
   'tweet_count': 9040},
  {'end': '2021-10-09T18:00:00.000Z',
   'start': '2021-10-09T17:00:00.000Z',
   'tweet_count': 10055},
  {'end': '2021-10-09T19:00:00.000Z',
   'start': '2021-10-09T18:00:00.000Z',
   'tweet_count': 11407},
  {'end': '2021-10-09T20:00:00.000Z',
   'start': '2021-10-09T19:00:00.000Z',
   'tweet_count': 8342},
  {'end': '2021-10-09T21:00:00.000Z',
   'start': '2021-10-09T20:00:00.000Z',
   'tweet_count': 7853},
  {'end': '2021-10-09T22:00:00.000Z',
   'start': '2021-10-09T21:00:00.000Z',
   'tweet_count': 5854},
  {'end': '2021-10-09T22:51:04.000Z',
   'start': '2021-10-09T22:00:00.000Z',
   'tweet_count': 4757}],
 'meta': {'total_tweet_count': 1268621}}

In [51]:
bnb_tweet_count_df = pd.DataFrame.from_dict(data["data"])

In [52]:
bnb_tweet_count_df.head()

                        end                     start  tweet_count
0  2021-10-02T23:00:00.000Z  2021-10-02T22:51:04.000Z          829
1  2021-10-03T00:00:00.000Z  2021-10-02T23:00:00.000Z         5932
2  2021-10-03T01:00:00.000Z  2021-10-03T00:00:00.000Z         6084
3  2021-10-03T02:00:00.000Z  2021-10-03T01:00:00.000Z         7327
4  2021-10-03T03:00:00.000Z  2021-10-03T02:00:00.000Z         8929

In [53]:
bnb_tweet_count_df["end"] = pd.to_datetime(bnb_tweet_count_df["end"])

In [54]:
bnb_tweet_count_df["start"] = pd.to_datetime(bnb_tweet_count_df["start"])

In [55]:
bnb_tweet_count_df.head()

                        end                     start  tweet_count
0 2021-10-02 23:00:00+00:00 2021-10-02 22:51:04+00:00          829
1 2021-10-03 00:00:00+00:00 2021-10-02 23:00:00+00:00         5932
2 2021-10-03 01:00:00+00:00 2021-10-03 00:00:00+00:00         6084
3 2021-10-03 02:00:00+00:00 2021-10-03 01:00:00+00:00         7327
4 2021-10-03 03:00:00+00:00 2021-10-03 02:00:00+00:00         8929

In [56]:
bnb_tweet_count_df = bnb_tweet_count_df.rename(columns={"end" : "Timestamp"})

In [57]:
bnb_tweet_count_df.head()

                  Timestamp                     start  tweet_count
0 2021-10-02 23:00:00+00:00 2021-10-02 22:51:04+00:00          829
1 2021-10-03 00:00:00+00:00 2021-10-02 23:00:00+00:00         5932
2 2021-10-03 01:00:00+00:00 2021-10-03 00:00:00+00:00         6084
3 2021-10-03 02:00:00+00:00 2021-10-03 01:00:00+00:00         7327
4 2021-10-03 03:00:00+00:00 2021-10-03 02:00:00+00:00         8929

In [58]:
bnb_tweet_count_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 169 entries, 0 to 168
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Timestamp    169 non-null    datetime64[ns, UTC]
 1   start        169 non-null    datetime64[ns, UTC]
 2   tweet_count  169 non-null    int64
dtypes: datetime64[ns, UTC](2), int64(1)
memory usage: 4.1 KB

In [59]:
engine = create_engine("sqlite:///bnb_tweet_count_df.db", echo=True)
sqlite_connection = engine.connect()

In [60]:
sqlite_table = "bnb_tweet_count_df1"
bnb_tweet_count_df.to_sql(sqlite_table, sqlite_connection, if_exists="fail")

2021-10-09 15:55:27,326 INFO sqlalchemy.engine.Engine PRAGMA main.table_info("bnb_tweet_count_df1")
2021-10-09 15:55:27,328 INFO sqlalchemy.engine.Engine [raw sql] ()
2021-10-09 15:55:27,332 INFO sqlalchemy.engine.Engine PRAGMA temp.table_info("bnb_tweet_count_df1")
2021-10-09 15:55:27,334 INFO sqlalchemy.engine.Engine [raw sql] ()
2021-10-09 15:55:27,340 INFO sqlalchemy.engine.Engine
CREATE TABLE bnb_tweet_count_df1 (
	"index" BIGINT,
	"Timestamp" TIMESTAMP,
	start TIMESTAMP,
	tweet_count BIGINT
)


2021-10-09 15:55:27,341 INFO sqlalchemy.engine.Engine [no key 0.00139s] ()
2021-10-09 15:55:27,349 INFO sqlalchemy.engine.Engine COMMIT
2021-10-09 15:55:27,350 INFO sqlalchemy.engine.Engine CREATE INDEX ix_bnb_tweet_count_df1_index ON bnb_tweet_count_df1 ("index")
2021-10-09 15:55:27,351 INFO sqlalchemy.engine.Engine [no key 0.00095s] ()
2021-10-09 15:55:27,358 INFO sqlalchemy.engine.Engine COMMIT
2021-10-09 15:55:27,360 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2021-10-09 15:55:27,363 INFO sqlalchemy.engine.Engine INSERT INTO bnb_tweet_count_df1 ("index", "Timestamp", start, tweet_count) VALUES (?, ?, ?, ?)
2021-10-09 15:55:27,364 INFO sqlalchemy.engine.Engine [generated in 0.00316s] ((0, '2021-10-02 23:00:00.000000', '2021-10-02 22:51:04.000000', 829), (1, '2021-10-03 00:00:00.000000', '2021-10-02 23:00:00.000000', 5932), (2, '2021-10-03 01:00:00.000000', '2021-10-03 00:00:00.000000', 6084), (3, '2021-10-03 02:00:00.000000', '2021-10-03 01:00:00.000000', 7327), (4, '2021-10-03 03:00:00.000000', '2021-10-03 02:00:00.000000', 8929), (5, '2021-10-03 04:00:00.000000', '2021-10-03 03:00:00.000000', 7509), (6, '2021-10-03 05:00:00.000000', '2021-10-03 04:00:00.000000', 6820), (7, '2021-10-03 06:00:00.000000', '2021-10-03 05:00:00.000000', 10235)  ... displaying 10 of 169 total bound parameter sets ...  (167, '2021-10-09 22:00:00.000000', '2021-10-09 21:00:00.000000', 5854), (168, '2021-10-09 22:51:04.000000', '2021-10-09 22:00:00.000000', 4757))
2021-10-09 15:55:27,368 INFO sqlalchemy.engine.Engine COMMIT